---
title: ""
output: html_document
---
#### Nuclear Explosions
```{r data, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(lubridate)
library(plotly)
library(leaflet)
library(googleVis)
library(tidyr)

# reading data
nuclear_explosions <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-20/nuclear_explosions.csv")

## Fakel
nuclear_explosions[nuclear_explosions$id_no == 72015, c("latitude", "longitude")] <- c(49.33, 35.31)
# Klivazh
nuclear_explosions[nuclear_explosions$id_no == 79059, c("latitude", "longitude")] <- c(48.13, 38.16)
# Tyumen RUSS
nuclear_explosions[nuclear_explosions$id_no == 85034, c("latitude", "longitude")] <- c(60.45, 72.47)
# PAMUK UZBEK
nuclear_explosions[nuclear_explosions$id_no == 68022, c("latitude", "longitude")] <- c(39.01, 65.05)

nuclear_explosions <- nuclear_explosions[nuclear_explosions$latitude != 0, ]




nuclear_explosions <- nuclear_explosions %>%
    mutate(date_long = ymd(date_long),
           purpose_grouped = ifelse(grepl("WR|ME|COMBAT", nuclear_explosions$purpose), "Weapons",
                            ifelse(grepl("PNE", nuclear_explosions$purpose), "Peaceful",
                                   ifelse(grepl("TRANSP|FMS|WE|SE|SAM", nuclear_explosions$purpose), "Research", "Undefined"))),
           depth = ifelse(depth > 0, depth*1000, depth),
           world_part = ifelse(latitude > 0 & longitude > 0,  "North-East",
                               ifelse(latitude > 0 & longitude < 0, "North-West",
                                      ifelse(latitude < 0 & longitude > 0, "South-East",
                                             ifelse(latitude < 0 & longitude < 0, "South-West", "strange")))),
           yield_avg = round((yield_lower + yield_upper)/2, digits = 1), 
           popup_nuc = paste("Country deployed: ", country, "<br/>",
                         "Date of explosion: ", as.character(date_long), "<br/>",
                         "Purpose of explosion: ", purpose_grouped, "<br/>",
                         "TNT equivalent: ", yield_avg, " kilotons", sep = ""))

nuclearIcons <- iconList(
    Weapons = makeIcon(iconUrl = "nuclear-bomb (1).png", iconWidth = 30, iconHeight = 30, iconAnchorX = 0, iconAnchorY = 30),
    Research = makeIcon(iconUrl = "science.png", iconWidth = 30, iconHeight = 30, iconAnchorX = 15, iconAnchorY = 15),
    Peaceful = makeIcon(iconUrl = "peace-symbol.png", iconWidth = 30, iconHeight = 30, iconAnchorX = 15, iconAnchorY = 30),
    Undefined = makeIcon(iconUrl = "question-mark-button.png", iconWidth = 30, iconHeight = 30, iconAnchorX = 15, iconAnchorY = 15)
)


```
Some statistical information

```{r, echo=FALSE, message=FALSE}
country_year <- nuclear_explosions %>%
    dplyr::group_by(year, country) %>%
    summarise(number_of_explosions = n(), total_mass_exploded = sum(yield_avg, na.rm = TRUE))
nuc_table <- as.data.frame.matrix(table(nuclear_explosions$country, nuclear_explosions$purpose_grouped))
nuc_table <- nuc_table %>% select(-Undefined)
nuc_table$Total <- rowSums(nuc_table)
nuc_table$Country <- c("China", "France", "India", "Pakistan", "UK", "USA", "USSR")
rownames(nuc_table) <- NULL
nuc_table <- select(nuc_table, Country, Weapons, Peaceful, Research, Total)
tab <- gvisTable(nuc_table)

```
```{r, echo=FALSE,results='asis'}
r <- as.data.frame.table(table(nuclear_explosions$world_part))

pie <- gvisPieChart(r, options = list(pieHole = 0.3, title = "Distribution of nuclear explosions by parts of the wold", width = 400))
PT <- gvisMerge(pie, tab, horizontal = TRUE)
```

```{r, results='asis', echo=FALSE}
wide_countries <- spread(country_year[, 1:3], key = country, value = number_of_explosions)
names(wide_countries)[2:8] <- c("China", "France", "India", "Pakistan", "UK", "USA", "USSR")
wide_countries <- as.data.frame.matrix(sapply(wide_countries, function(x){ifelse(is.na(x), 0, x) }))
line <- gvisLineChart(wide_countries, xvar = "year", yvar = c("China", "France", "India", "Pakistan", "UK", "USA", "USSR"),
                      options = list(
                          height = 600,
                          curveType= "function",
                          title = "Number of explosions by the countries by years",
                          vAxis = '{title:"Number of explosions"}',
                          hAxis = '{title:"Year"}'
                          ))
all <- gvisMerge(PT, line, horizontal = FALSE)
print(all, "chart")
```




```{r, echo=FALSE}
t <- plot_ly(r, type = "pie", labels = ~Var1, values = ~Freq, 
             textposition = 'inside',
             textinfo = 'label+percent',
             hoverinfo = 'text',
             text = ~paste(Var1, "<br>", Freq, 'explosions'),
             marker = list(line = list(color = 'black', width = 1)),
             showlegend = FALSE
             ) %>%
    layout(title = "Distribution of nuclear explosions by parts of the wold")

```

All nuclear explosions on map
```{r, echo=FALSE}
g <- leaflet(nuclear_explosions) %>% 
    addTiles() %>% 
    addMarkers(lng = ~longitude, lat = ~latitude, 
               clusterOptions = markerClusterOptions(), icon = ~nuclearIcons[purpose_grouped],
               popup = ~popup_nuc, label = ~country)
g